COUNTY_PREFIXES = {
        "Carlow": "CW",
        "Cavan": "CN",
        "Clare": "CE",
        "Cork": "C",
        "Donegal": "DL",
        "Dublin": "D",
        "Galway": "G",
        "Kerry": "KY",
        "Kildare": "KE",
        "Kilkenny": "KK",
        "Laois": "LS",
        "Leitrim": "LM",
        "Limerick": "LK",
        "Longford": "LD",
        "Louth": "LH",
        "Mayo": "MO",
        "Meath": "MH",
        "Monaghan": "MN",
        "Offaly": "OY",
        "Roscommon": "RN",
        "Sligo": "SO",
        "Tipperary": "TY",
        "Waterford": "WD",
        "Westmeath": "WH",
        "Wexford": "WX",
        "Wicklow": "WW",
    }

COUNTY_CHOICES = [
    ("Carlow", "Carlow"),
    ("Cavan", "Cavan"),
    ("Clare", "Clare"),
    ("Cork", "Cork"),
    ("Donegal", "Donegal"),
    ("Dublin", "Dublin"),
    ("Galway", "Galway"),
    ("Kerry", "Kerry"),
    ("Kildare", "Kildare"),
    ("Kilkenny", "Kilkenny"),
    ("Laois", "Laois"),
    ("Leitrim", "Leitrim"),
    ("Limerick", "Limerick"),
    ("Longford", "Longford"),
    ("Louth", "Louth"),
    ("Mayo", "Mayo"),
    ("Meath", "Meath"),
    ("Monaghan", "Monaghan"),
    ("Offaly", "Offaly"),
    ("Roscommon", "Roscommon"),
    ("Sligo", "Sligo"),
    ("Tipperary", "Tipperary"),
    ("Waterford", "Waterford"),
    ("Westmeath", "Westmeath"),
    ("Wexford", "Wexford"),
    ("Wicklow", "Wicklow"),
]
