# Generated by Django 5.1.6 on 2025-05-13 09:05

import ce.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='eg. 20, 21, 21')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppsn', models.CharField(max_length=9, unique=True, validators=[ce.models.validate_ppsn], verbose_name='PPS Number')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits only).', regex='^\\d+$')], verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('emerg_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits only).', regex='^\\d+$')], verbose_name='Phone Number')),
                ('scheme_start_date', models.DateField()),
                ('scheme_finish_date', models.DateField(blank=True, null=True)),
                ('manual_start_date', models.DateField()),
                ('manual_finish_date', models.DateField(blank=True, null=True)),
                ('bank_iban', models.CharField(max_length=22, unique=True, validators=[ce.models.validate_iban], verbose_name='Bank IBAN')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ce.department')),
            ],
        ),
        migrations.CreateModel(
            name='HolidaySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hol_hours_entitled', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hol_hours_taken', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hol_hours_in_lieu', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sick_cert_hours_entitled', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sick_cert_hours_taken', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sick_uncert_hours_entitled', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sick_uncert_hours_taken', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calculated_on', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays_summaries', to='ce.participant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_summaries', to='ce.project')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, help_text='Use negative for time off, positive for extra work.', max_digits=5)),
                ('type', models.CharField(choices=[('take_hours', 'Take Hours'), ('add_hours', 'Add Hours'), ('sick_cert', 'Sick Leave (Cert)'), ('sick_uncert', 'Sick Leave (No Cert)'), ('other', 'Other')], default='take_hours', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ce.department')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='ce.participant')),
                ('project', models.ForeignKey(help_text='Project associated with this holiday Event', on_delete=django.db.models.deletion.CASCADE, related_name='holiday_event', to='ce.project')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('gov_code', models.CharField(max_length=50, unique=True)),
                ('app_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('use_departments', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('current_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_schemes', to='ce.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='ce.scheme'),
        ),
        migrations.AddField(
            model_name='participant',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ce.scheme'),
        ),
        migrations.AddField(
            model_name='department',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ce.scheme'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('scheme', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('scheme', 'name')},
        ),
    ]
