# Generated by Django 5.1.6 on 2025-04-18 18:09

import ce.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppsn', models.CharField(max_length=9, unique=True, validators=[ce.models.validate_ppsn], verbose_name='PPS Number')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits only).', regex='^\\d+$')], verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('emerg_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits only).', regex='^\\d+$')], verbose_name='Phone Number')),
                ('manual_expire', models.DateField()),
                ('bank_iban', models.CharField(max_length=22, unique=True, validators=[ce.models.validate_iban], verbose_name='Bank IBAN')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ce.department')),
            ],
        ),
    ]
